# Generated by Django 5.2.2 on 2025-06-16 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_usertoken_token_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
